name: Update README with Contributors

on:
  # Run the workflow when changes are pushed to the main branch
  push:
    branches:
      - main
  # Or schedule it to run daily
  schedule:
    - cron: '0 0 * * *'  # Runs every day at midnight UTC

jobs:
  update-readme:
    runs-on: ubuntu-latest

    steps:
    # Checkout the repository code
    - name: Checkout repository
      uses: actions/checkout@v3

    # Set up Python environment
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    # Run the Python script to update README.md
    - name: Run script to update README.md
      run: |
        python generate_readme.py

    # Commit and push changes to the README.md
    - name: Commit and push changes
      run: |
        git config --global user.name 'github-actions[bot]'
        git config --global user.email 'github-actions[bot]@users.noreply.github.com'
        git add README.md
        git commit -m "Update contributors section"
        git push
